openapi: "3.0.0"
info:
  title: OpenAPI Test
  description: Bla Blub
  version: Wed Oct 18 14:26:19 CEST 2017
  contact:
    name: thor
paths:
  /:
    get:
      summary: Workflow metadata
      responses:
        "200":
          description: Show metadata of the workflow
          content:
            application/vnd.mason+json:
              schema:
                $ref: "#/components/schemas/Workflow" 
  "/:job-pool":
    post:
      summary: Executes a job from the workflow
      operationId: executeJob
      requestBody:
        description: Simple input parameters for the job
        content:
          application/json:
            examples:
              default:
                summary: Default values from the workflow
                value: |
                  {
                    "string-input" : {
                      "string" : ""
                    },
                    "int-input" : {
                      "integer" : 0
                    },
                    "json-input" : {
                      "a" : "b"
                    }
                  }
      responses:
        "200":
          description: Status and result of the job
          content:
            application/vnd.mason+json:
              schema:
                $ref: "#/components/schemas/Job"             
    
  
components:
  schemas:
    Workflow:
      properties:
        path:
          type: string
        owner:
          type: string
            
    InputParameters:
      $ref: ./input-parameters.json
      
    Job:
      properties:
        id:
          type: string
        inputParameters:
          $ref: '#/components/schemas/InputParameters'